# Generated by Django 4.2.2 on 2023-06-13 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="subject",
            new_name="question",
        ),
    ]
